У цьому домашньому завданні ми будемо працювати з набором даних Tips. Нижче інформація про нього.

**Про датасет:**

Tips - це датасет, який містить інформацію про рахунки та чайові в ресторані.

**Колонки датасету:**
- `total_bill` - загальна сума рахунку (долари)
- `tip` - розмір чайових (долари)
- `sex` - стать відвідувача (Male/Female)
- `smoker` - чи курить (Yes/No)
- `day` - день тижня (Thur/Fri/Sat/Sun)
- `time` - час відвідування (Lunch/Dinner)
- `size` - розмір групи (кількість людей)

**Джерело:** Оригінальні дані зібрані в одному з американських ресторанів у 1990-х роках. Скачати і переглянути набір даних можна тут: https://www.kaggle.com/datasets/sakshisatre/tips-dataset

А також ми вже вивантажили файл з даними і завантажили вам у Матеріали до цього модуля.




**1. Завантаження та огляд**

Завантажте датасет Tips (Чайові) з файла у матеріалах `tips.csv`.

Виведіть (кожен пункт оцінюється в 0.5 бала):
- Перші 5 рядків
- Розмір датасету (shape)
- Назви всіх колонок
- Інформацію про типи даних (info)

In [2]:
import pandas as pd

In [4]:
df = pd.read_csv('tips.csv')

In [5]:
display(df.head(5))

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [6]:
display(df.head())

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [7]:
display(df.shape)
display(df.columns)
display(list(df.columns))

(244, 7)

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size']

In [8]:
display(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object
 3   smoker      244 non-null    object
 4   day         244 non-null    object
 5   time        244 non-null    object
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB

None

**2. Базова вибірка даних**

Виберіть та виведіть (кожен пункт оцінюється в 0.5 бала):
- Колонку `total_bill` (загальний рахунок)
- Колонки `total_bill` та `tip` (чайові) разом
- Перші 10 рядків
- Рядок з індексом 5

In [9]:
display(df['total_bill'])
display(df.total_bill)

0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: float64

0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: float64

In [10]:
display(df[['total_bill', 'tip']])

     total_bill   tip
0         16.99  1.01
1         10.34  1.66
2         21.01  3.50
3         23.68  3.31
4         24.59  3.61
..          ...   ...
239       29.03  5.92
240       27.18  2.00
241       22.67  2.00
242       17.82  1.75
243       18.78  3.00

[244 rows x 2 columns]

In [11]:
display(df.head(10))
display(df.loc[0:9])

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
5       25.29  4.71    Male     No  Sun  Dinner     4
6        8.77  2.00    Male     No  Sun  Dinner     2
7       26.88  3.12    Male     No  Sun  Dinner     4
8       15.04  1.96    Male     No  Sun  Dinner     2
9       14.78  3.23    Male     No  Sun  Dinner     2

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
5       25.29  4.71    Male     No  Sun  Dinner     4
6        8.77  2.00    Male     No  Sun  Dinner     2
7       26.88  3.12    Male     No  Sun  Dinner     4
8       15.04  1.96    Male     No  Sun  Dinner     2
9       14.78  3.23    Male     No  Sun  Dinner     2

In [12]:
display(df.loc[5])

total_bill     25.29
tip             4.71
sex             Male
smoker            No
day              Sun
time          Dinner
size               4
Name: 5, dtype: object

**3. Фільтрація даних**

Відфільтруйте повний набір даних та виведіть (кожен пункт оцінюється в 0.5 бала):
- Всі рахунки більше 20 доларів (`total_bill > 20`)
- Всі відвідувачі-жінки (`sex == 'Female'`)
- Рахунки на вечерю (`time == 'Dinner'`)
- Рахунки на вечерю з сумою чеку більше 30 доларів

Для виведення результатів фільтрації:
- зберегти результат у окрему змінну
- показати кількість записів у відфільтрованому наборі
- вивести перші 5 записів відфільтрованого набору.

In [13]:
total_bill_greater_than_20_dollars = df[df['total_bill'] > 20]
rows_cnt_1 = total_bill_greater_than_20_dollars.shape[0]
print(f'Результат фільтрації: {rows_cnt_1} рядків')
display(total_bill_greater_than_20_dollars.head())

Результат фільтрації: 97 рядків

   total_bill   tip     sex smoker  day    time  size
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
5       25.29  4.71    Male     No  Sun  Dinner     4
7       26.88  3.12    Male     No  Sun  Dinner     4

In [14]:
female_customers = df[df['sex'] == 'Female']
rows_cnt_2 = female_customers.shape[0]
print(f'Результат фільтрації: {rows_cnt_2} рядків')
display(female_customers.head())

Результат фільтрації: 87 рядків

    total_bill   tip     sex smoker  day    time  size
0        16.99  1.01  Female     No  Sun  Dinner     2
4        24.59  3.61  Female     No  Sun  Dinner     4
11       35.26  5.00  Female     No  Sun  Dinner     4
14       14.83  3.02  Female     No  Sun  Dinner     2
16       10.33  1.67  Female     No  Sun  Dinner     3

In [15]:
dinner_only = df[df['time'] == 'Dinner']
rows_cnt_3 = dinner_only.shape[0]
print(f'Результат фільтрації: {rows_cnt_3} рядків')
display(dinner_only.head())

Результат фільтрації: 176 рядків

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [16]:
dinner_greater_than_30_dollars = df[(df['time'] == 'Dinner') & (df['total_bill'] > 30)]
rows_cnt_4 = dinner_greater_than_30_dollars.shape[0]
print(f'Результат фільтрації: {rows_cnt_4} рядків')
display(dinner_greater_than_30_dollars.head())

Результат фільтрації: 27 рядків

    total_bill   tip     sex smoker  day    time  size
11       35.26  5.00  Female     No  Sun  Dinner     4
23       39.42  7.58    Male     No  Sat  Dinner     4
39       31.27  5.00    Male     No  Sat  Dinner     3
44       30.40  5.60    Male     No  Sun  Dinner     4
47       32.40  6.00    Male     No  Sun  Dinner     4

---

**4. Описова статистика**

Обчисліть (кожен пункт оцінюється в 0.5 бала):
- Середній розмір рахунку на всьому наборі даних
- Максимальні чайові
- Кількість пропущених значень у всіх колонках
- Скільки в наборі даних рахунків за обіди і за вечері

In [17]:
mean_total_bill = df['total_bill'].mean()
print(f"Середній розмір рахунку: {mean_total_bill:.2f}")

max_tip = df['tip'].max()
print(f"Максимальні чайові: {max_tip}")

Середній розмір рахунку: 19.79
Максимальні чайові: 10.0

In [18]:
display(df.isnull().sum())

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [20]:
display(df.time.value_counts())

time
Dinner    176
Lunch      68
Name: count, dtype: int64

---

**5. Статистика із групуванням**

Обчисліть (кожен пункт оцінюється в 0.5 бала):
- Середній рахунок за статтю (groupby `sex`)
- Середні чайові за днем тижня (groupby `day`)
- Скільки відвідувачів у кожен день

In [27]:
by_sex = df.groupby('sex')['total_bill'].mean()
print('Середній рахунок за статтю:')
display(by_sex)

Середній рахунок за статтю:

sex
Female    18.056897
Male      20.744076
Name: total_bill, dtype: float64

In [28]:
by_day = df.groupby('day')['tip'].mean()
print('Середні чайові за днем тижня')
display(by_day)

Середні чайові за днем тижня

day
Fri     2.734737
Sat     2.993103
Sun     3.255132
Thur    2.771452
Name: tip, dtype: float64

In [38]:
# Якщо треба порахувати, скільки всього людей
visitors_cnt_1 = df.groupby('day')['size'].sum()
print('Скільки відвідувачів у кожен день:')
display(visitors_cnt_1)
print('---------------------------------\n')

# Якщо мається на увазі 1 рахунок = 1 відвідувач(візит)
visitors_cnt_2 = df.groupby('day').size()
print('Скільки відвідувачів у кожен день:')
display(visitors_cnt_2)
print('---------------------------------\n')
# або
visitors_cnt_3 = df['day'].value_counts()
print('Скільки відвідувачів у кожен день:')
display(visitors_cnt_3)

Скільки відвідувачів у кожен день:

day
Fri      40
Sat     219
Sun     216
Thur    152
Name: size, dtype: int64

---------------------------------

Скільки відвідувачів у кожен день:

day
Fri     19
Sat     87
Sun     76
Thur    62
dtype: int64

---------------------------------

Скільки відвідувачів у кожен день:

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

---

**6. Створення нової колонки**

Створіть нову колонку `tip_percentage` - відсоток чайових від загальної суми рахунку.
Виведіть перші 10 рядків з новою колонкою.

In [52]:
df['tip_percentage'] = ((df['tip'] / df['total_bill']) * 100).round(2)
df.head(10)

   total_bill   tip     sex smoker  day    time  size  tip_percentage
0       16.99  1.01  Female     No  Sun  Dinner     2            5.94
1       10.34  1.66    Male     No  Sun  Dinner     3           16.05
2       21.01  3.50    Male     No  Sun  Dinner     3           16.66
3       23.68  3.31    Male     No  Sun  Dinner     2           13.98
4       24.59  3.61  Female     No  Sun  Dinner     4           14.68
5       25.29  4.71    Male     No  Sun  Dinner     4           18.62
6        8.77  2.00    Male     No  Sun  Dinner     2           22.81
7       26.88  3.12    Male     No  Sun  Dinner     4           11.61
8       15.04  1.96    Male     No  Sun  Dinner     2           13.03
9       14.78  3.23    Male     No  Sun  Dinner     2           21.85

---

**7. Сортування**

Відсортуйте датасет і виведіть результат сортування в кожному випадку окремо (кожен пункт оцінюється в 0.5 бала):
- За розміром рахунку (зростання)
- За чайовими (спадання)

Додатково виведіть топ-5 найбільших чайових використовуючи метод `nlargest`.

In [53]:
sorted_by_total_bill_asc = df.sort_values('total_bill')
display(sorted_by_total_bill_asc)

     total_bill    tip     sex smoker   day    time  size  tip_percentage
67         3.07   1.00  Female    Yes   Sat  Dinner     1           32.57
92         5.75   1.00  Female    Yes   Fri  Dinner     2           17.39
111        7.25   1.00  Female     No   Sat  Dinner     1           13.79
172        7.25   5.15    Male    Yes   Sun  Dinner     2           71.03
149        7.51   2.00    Male     No  Thur   Lunch     2           26.63
..          ...    ...     ...    ...   ...     ...   ...             ...
182       45.35   3.50    Male    Yes   Sun  Dinner     3            7.72
156       48.17   5.00    Male     No   Sun  Dinner     6           10.38
59        48.27   6.73    Male     No   Sat  Dinner     4           13.94
212       48.33   9.00    Male     No   Sat  Dinner     4           18.62
170       50.81  10.00    Male    Yes   Sat  Dinner     3           19.68

[244 rows x 8 columns]

In [54]:
sorted_by_tip_desc = df.sort_values('tip', ascending=False)
display(sorted_by_tip_desc)

     total_bill    tip     sex smoker   day    time  size  tip_percentage
170       50.81  10.00    Male    Yes   Sat  Dinner     3           19.68
212       48.33   9.00    Male     No   Sat  Dinner     4           18.62
23        39.42   7.58    Male     No   Sat  Dinner     4           19.23
59        48.27   6.73    Male     No   Sat  Dinner     4           13.94
141       34.30   6.70    Male     No  Thur   Lunch     6           19.53
..          ...    ...     ...    ...   ...     ...   ...             ...
0         16.99   1.01  Female     No   Sun  Dinner     2            5.94
111        7.25   1.00  Female     No   Sat  Dinner     1           13.79
92         5.75   1.00  Female    Yes   Fri  Dinner     2           17.39
67         3.07   1.00  Female    Yes   Sat  Dinner     1           32.57
236       12.60   1.00    Male    Yes   Sat  Dinner     2            7.94

[244 rows x 8 columns]

In [55]:
top_5_tips = df.nlargest(5, 'tip')['tip']
display(top_5_tips)

170    10.00
212     9.00
23      7.58
59      6.73
141     6.70
Name: tip, dtype: float64